### ISSUE TITLE
Informe de Entrevista

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/entrevista-equipo-bjy#1]
[Informe Entrevista.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-equipo-bjy/files/7140154/Informe.Entrevista.pdf)

Anexo el informe de Entrevista.
Equipo:
Brisa Osorio Ramírez.
Jazmín López Riveros.
Yabin España Aparicio

**Comment by KarlaV0** [comment]
Muy buen trabajo 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
